name: .NET Core

jobs:
  build:
    on:
      push:
        branches-ignore:
          - master
        runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: |
        DOTNET_CLI_TELEMETRY_OPTOUT=1
        dotnet build --nologo --configuration Release
        dotnet pack --no-build -c Release -o nuget
    - name: MyGet push
      run: |
        source=https://www.myget.org/F/fsharp-collections-immutable/api/v3/index.json
        key=${{secrets.MyGet_Key}}
        dotnet nuget push -s $source -k $key nuget/*.nupkg

  release:
    on:
      create:
        types:
          - tag
        branches:
          - master
    steps:
      - name: Release Version
        run: |
          dotnet pack -c Release -o nuget
          source=https://api.nuget.org/v3/index.json
          key=${{secrets.NuGet_Key}}
          # dotnet nuget push -s $source -k $key nuget/*.nupkg
          echo "This should only run on tag create"
