name: .NET Core

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: |
        DOTNET_CLI_TELEMETRY_OPTOUT=1
        dotnet build --nologo --configuration Release
        dotnet pack --no-build -c Release
    - name: MyGet push
      run: |
        source=https://www.myget.org/F/fsharp-collections-immutable/api/v3/index.json
        key=${{secrets.MyGet_Key}}
        dotnet nuget push -s $source -k $key nuget/*.nupkg


